name: niftyoptions
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - pandas
  - streamlit
  - numpy
  - matplotlib
  - scipy
  - pyside6
  - qtbase
  - matplotlib-base
  - ...

