name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies for proper import resolution
        pip install -r requirements.txt || echo "Failed to install some dependencies, continuing..."
    - name: Analysing the code with pylint
      run: |
        # Run pylint with relaxed settings for initial analysis
        pylint --disable=all --enable=E,F $(git ls-files '*.py') || true
        echo "Full pylint analysis:"
        pylint $(git ls-files '*.py') --exit-zero
