name: Streamlit App Deploy Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Streamlit and dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install streamlit pandas yfinance plotly pyyaml websockets

      - name: Run Streamlit App in Background
        run: |
          source venv/bin/activate
          nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &
          sleep 15

      - name: Test if Streamlit is running
        run: |
          curl --retry 3 --retry-delay 5 --fail http://localhost:8501 || (echo "Streamlit failed to start" && exit 1)

      - name: Success Notice
        run: echo "✅ Streamlit app ran successfully in CI."
